/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*workspace :
 * ****************************************************************************
 * User:Juan Gutierrez
 * User_email:jdgutierrezp@unal.edu.co
 * ****************************************************************************
 */
//ESTRUCTURA COMPLETA
//#define
//includes
//Deficnion de variables
//cabecera de funciones
//funcion main
	//funciones
	//while
		//blicky condicional
		//EXTI1 condicional (exti de decricimiento)
		//EXTI0 conditional (exti de crecicminto)
//functions

//includes
#include <stdint.h>
#include <stm32f4xx.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//deficinion de variables
uint8_t  flag = 0;  //INDICADOR PARA EL BLINKY
volatile uint16_t counter_exti =0; //CONTADOR DE EVENTOS
volatile uint8_t increment_counter =0;	//VOLATILE-->NO GUARDA EL CONTEXTO DE LA INTERUPCION
volatile uint8_t decrement_counter =0;
volatile uint8_t digitos[4] = {0, 0, 0, 0}; // LOS CUATRO NUMEROS QUE SE MUESTRAN
volatile uint8_t digito_actual = 0;         // LOS CUATRO DIGITOS SEGUN DATASHEED D1, D2, D3, D4

//cabecera de funciones
void pines(void);		//FUNCION QUE CONFIGURA DE LOS PINES QUE SE VAN A UTILIZAR
void blinky(void);		//FUNCION PARA EL FUNCIONAMIENTO DEL BLINKY
void exti_1(void);		//FUNCION PARA FUNCIONAMINTO DE LA INTRUPCION 1
void exti_0(void);		//FUNCION PARA LA INTERUPCION 0
void separar_digitos(void);
void configurar_timer2_display(void);
void decodificar_7seg(uint8_t numero);

//funcion main
int main(void){
	pines();
	blinky();
	exti_1();
	exti_0();
	separar_digitos();
	configurar_timer2_display();

	while(1){
		if(flag){		//CONDICIONAL PARA EL FUNCIONAMINTO DEL BLINKY
			flag = 0;
			GPIOH->ODR ^= GPIO_ODR_OD1;

		}
		if(increment_counter == 1){			//condicional del relaciones con el EXTI1
		            if(counter_exti < 9999) {
		                counter_exti++;
		            } else {
		                counter_exti = 0; // VELVE A 0 SI SE PASA DE 9999
		            }
		            increment_counter = 0;
		            separar_digitos(); // ACTUALIZA EL ARREGLO HECHO EN EL CONDICIONAL
		        }

		        if(decrement_counter == 1){ 	//condicional del relaciones con el EXTI0
		            if(counter_exti > 0) {
		                counter_exti--;
		            } else {
		                counter_exti = 9999; // VUELVE A 9999 SI SE BAJA POR DEBAJO DE 0
		            }
		            decrement_counter = 0;
		            separar_digitos(); // ACTUALIZA EL ARREGLO HECHO EN EL CONDICIONAL
		        }
	}
	return 0;

}

void pines(void){

	// PRENDEMOS LOS RELOJES NECESARIOS
	// GPIOB
	RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOBEN);// ESTAN EN EL MISMO BUS --LIMPIEZA DEL REGISTRO
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;	//ACTIVACION DE LA SEÑAL DE RELOJCON LA CONFIGURACION

	RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOCEN);//GPIOC
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

	RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIODEN);//GPIOD
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;


	//configuracion puertos generales- SALIDA
	//PB

	GPIOB->MODER &= ~(GPIO_MODER_MODE7 | GPIO_MODER_MODE8 | GPIO_MODER_MODE9);//LIPIEZA DE LOS PUERTOS EN REGISTRO MODER
	GPIOB->MODER |= (GPIO_MODER_MODE7_0 | GPIO_MODER_MODE8_0 | GPIO_MODER_MODE9_0);// ACTIVACIOND DE PUERTOS EN REGISTRO MODDER DE BER 10

	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT7 | GPIO_OTYPER_OT8 | GPIO_OTYPER_OT9 );//LIPIEZA DE LOS PUERTOS EN REGISTRO OTIPER

	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR7 | GPIO_OSPEEDER_OSPEEDR8 | GPIO_OSPEEDER_OSPEEDR9);//LIPIEZA DE LOS PUERTOS EN REGISTRO OSSPEDEER
	GPIOB->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR7_1 | GPIO_OSPEEDER_OSPEEDR8_1 | GPIO_OSPEEDER_OSPEEDR9_1);// PONER 10 EN LA POSCION 14  PARA FAST MODE

	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPD7 | GPIO_PUPDR_PUPD8 | GPIO_PUPDR_PUPD9);	// LIMPEZA DE PUERTO  PUPDR - SE DEJA EN 00

	GPIOB->ODR &= ~(GPIO_ODR_ODR_7 | GPIO_ODR_ODR_8  | GPIO_ODR_ODR_9); //LIMPESZA DEL PUERTO ODR
	GPIOB->ODR |= (GPIO_ODR_ODR_7 | GPIO_ODR_ODR_8 | GPIO_ODR_ODR_9);// ACTIVACION DEL PUERTO OD SE DEBE POR EN 1 PARA LA SALIDA - SE COMINEZA PAGADO


	//configuracion puertos generales- SALIDA
	//PC

	GPIOC->MODER &= ~(GPIO_MODER_MODE6 | GPIO_MODER_MODE8 | GPIO_MODER_MODE9 | GPIO_MODER_MODE10| GPIO_MODER_MODE11 | GPIO_MODER_MODE12 | GPIO_MODER_MODE13);//LIPIEZA DE LOS PUERTOS EN REGISTRO MODER
	GPIOC->MODER |= (GPIO_MODER_MODE6_0 | GPIO_MODER_MODE8_0 | GPIO_MODER_MODE9_0 | GPIO_MODER_MODE10_0 | GPIO_MODER_MODE11_0 | GPIO_MODER_MODE12_0 | GPIO_MODER_MODE13_0);// ACTIVACIOND DE PUERTOS EN REGISTRO MODDER DE BER 10

	GPIOC->OTYPER &= ~(GPIO_OTYPER_OT6 | GPIO_OTYPER_OT8 | GPIO_OTYPER_OT9 | GPIO_OTYPER_OT10 | GPIO_OTYPER_OT11 | GPIO_OTYPER_OT12 | GPIO_OTYPER_OT13 );//LIPIEZA DE LOS PUERTOS EN REGISTRO OTIPER

	GPIOC->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR6  | GPIO_OSPEEDER_OSPEEDR8 | GPIO_OSPEEDER_OSPEEDR9 | GPIO_OSPEEDER_OSPEEDR10 | GPIO_OSPEEDER_OSPEEDR11 | GPIO_OSPEEDER_OSPEEDR12 | GPIO_OSPEEDER_OSPEEDR13);//LIPIEZA DE LOS PUERTOS EN REGISTRO OSSPEDEER
	GPIOC->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR6_1  | GPIO_OSPEEDER_OSPEEDR8_1 | GPIO_OSPEEDER_OSPEEDR9_1 | GPIO_OSPEEDER_OSPEEDR10_1 | GPIO_OSPEEDER_OSPEEDR11_1 | GPIO_OSPEEDER_OSPEEDR12_1 | GPIO_OSPEEDER_OSPEEDR13_1);// PONER 10 EN LA POSCION 14  PARA FAST MODE

	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPD6 | GPIO_PUPDR_PUPD8 | GPIO_PUPDR_PUPD9 | GPIO_PUPDR_PUPD10 | GPIO_PUPDR_PUPD11 | GPIO_PUPDR_PUPD12 | GPIO_PUPDR_PUPD13);	// LIMPEZA DE PUERTO  PUPDR - SE DEJA EN 00

	GPIOC->ODR &= ~(GPIO_ODR_ODR_6 | GPIO_ODR_ODR_8  | GPIO_ODR_ODR_9 | GPIO_ODR_ODR_10  | GPIO_ODR_ODR_11| GPIO_ODR_ODR_12  | GPIO_ODR_ODR_13); //LIMPESZA DEL PUERTO ODR
	GPIOC->ODR |= (GPIO_ODR_ODR_6 | GPIO_ODR_ODR_8  | GPIO_ODR_ODR_9 | GPIO_ODR_ODR_10  | GPIO_ODR_ODR_11| GPIO_ODR_ODR_12  | GPIO_ODR_ODR_13);// ACTIVACION DEL PUERTO OD SE DEBE POR EN 1 PARA LA SALIDA - SE COMINEZA PAGADO

	//configuracion puertos generales- SALIDA
	//PD

	GPIOD->MODER &= ~(GPIO_MODER_MODE2);//LIPIEZA DE LOS PUERTOS EN REGISTRO MODER
	GPIOD->MODER |= (GPIO_MODER_MODE2_0);// ACTIVACIOND DE PUERTOS EN REGISTRO MODDER DE BER 10

	GPIOD->OTYPER &= ~(GPIO_OTYPER_OT2);//LIPIEZA DE LOS PUERTOS EN REGISTRO OTIPER

	GPIOD->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR2);//LIPIEZA DE LOS PUERTOS EN REGISTRO OSSPEDEER
	GPIOD->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR2_1);// PONER 10 EN LA POSCION 14  PARA FAST MODE

	GPIOD->PUPDR &= ~(GPIO_PUPDR_PUPD2);	// LIMPEZA DE PUERTO  PUPDR - SE DEJA EN 00

	GPIOD->ODR &= ~(GPIO_ODR_ODR_2); //LIMPESZA DEL PUERTO ODR
	GPIOD->ODR |= (GPIO_ODR_ODR_2);// ACTIVACION DEL PUERTO OD SE DEBE POR EN 1 PARA LA SALIDA - SE COMINEZA PAGADO


	//CONFIGURACION PINES ENTRADA SIMPLE
	//PIN B (PB0)

	GPIOB->MODER &= ~(GPIO_MODER_MODE0);
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPD0);// MODO NO PULL-UP NO PULL-DOWN


	//PIN C (PC1)
	GPIOC->MODER &= ~(GPIO_MODER_MODE1); // Modo entrada
	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPD1); // MODO NO PULL-UP NO PULL-DOWN

}

void blinky(void){
	// 1. CONFIGURACIÓN DEL PIN PH1 (Se mantiene igual)
	RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOHEN);//LIMPIEZA DEL REGISTRO
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOHEN;	//ACTIVACION DE SEÑAL DE RELOJ

	GPIOH->MODER &= ~(GPIO_MODER_MODE1);
	GPIOH->MODER |= (GPIO_MODER_MODE1_0);

	GPIOH->OTYPER &= ~(GPIO_OTYPER_OT1);

	GPIOH->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR1);
	GPIOH->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR1_1);

	GPIOH->PUPDR &= ~(GPIO_PUPDR_PUPD1);

	GPIOH->ODR &= ~(GPIO_ODR_OD1);
	GPIOH->ODR |= (GPIO_ODR_OD1);

	// 2. CONFIGURACIÓN DEL TIMER 3 (Para el parpadeo)
	RCC->APB1ENR &= ~(RCC_APB1ENR_TIM3EN);
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN; // Activar reloj del TIM3

	TIM3->PSC = 16000 - 1; // Preescaler para que cuente cada 1 ms
	TIM3->ARR = 250 - 1;   // Interrupción cada 500 ms (Medio segundo)

	TIM3->CNT = 0; // Iniciar contador en 0

	TIM3->DIER &= ~(TIM_DIER_UIE);
	TIM3->DIER |= TIM_DIER_UIE; // Activar interrupción del Timer

	__NVIC_EnableIRQ(TIM3_IRQn); // Matricular el TIM3 en el NVIC

	TIM3->CR1 &= ~(TIM_CR1_DIR); // Contar hacia arriba
	TIM3->CR1 &= ~(TIM_CR1_ARPE);
	TIM3->CR1 |= TIM_CR1_ARPE;
	TIM3->CR1 |= TIM_CR1_CEN; // Arrancar el Timer 3
}
//ISR PARA EL BLINKY
void TIM3_IRQHandler(void){
	//VERIFICACION QUE SE GENERA LA INTERUPCIOM
	if (TIM3->SR & TIM_SR_UIF){
		TIM3->SR &= ~ TIM_SR_UIF;// REALIZACION DE ACCION DE RESPUESTA
		flag = 1;
	}
}

void exti_0(void){
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;//ACTIVACION DE SEÑAL DE RELOJ DEL BUS DODE YACE EL SYSCFG

	SYSCFG->EXTICR[0] &= ~(SYSCFG_EXTICR1_EXTI0); //[0] PARA UTILIZAR EL PB0. EQUIVALENCIA PB0 ESTA EN CR1
	SYSCFG->EXTICR[0] |= (SYSCFG_EXTICR1_EXTI0_PB);//SE ESCRIBE 1 EN EL PB0

	EXTI->FTSR |= EXTI_FTSR_TR0;//CONFIGURACION DE FLANCO BAJADA--ESCRITURA DE 1

	__NVIC_EnableIRQ(EXTI0_IRQn);//REGISTRO LA INTERRPCION EN EL NVIC

	EXTI->PR |= EXTI_PR_PR0;//LIMPIEZA DE LA BANDERA RELACIONADA CON EL EXTI-SEGUN REFERENCE MANUAL SE LIMPIA CON 1

	EXTI->IMR |= EXTI_IMR_IM0;//ACTIVACION DE LA INTERRUPCION (IMR)- SE ESCRIBE 1 EN EL O-->PB0


	//BUSCAR LAS ISR --> STARTUP-->VECTORES COMPLETOS
	//

}

//ISR PARA EL EXTI0
// VERIFICAR QUE EL PR ESTA LEVATADO
//
void EXTI0_IRQHandler(void){		// SE INDICA QUE SE VA A SER Y EN EL MAIN SE HACE
	if(EXTI->PR && EXTI_PR_PR0){ 	//VERIFICACION
		EXTI->PR |= EXTI_PR_PR0;	//LIMPIEZA DE INTERRPCION
		decrement_counter=1;		//VA A SER EVALUADA EN EL MAIN

	}
}
// EXTI1 //EXTI DE DECRIMENTO

void exti_1(void){
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;//ACTIVACION DE SEÑAL DE RELOJ DEL BUS DODE YACE EL SYSCFG

	SYSCFG->EXTICR[0] &= ~(SYSCFG_EXTICR1_EXTI1); //[0] PARA UTILIZAR EL PC0. EQUIVALENCIA PC0 ESTA EN CR1
	SYSCFG->EXTICR[0] |= (SYSCFG_EXTICR1_EXTI1_PC);//SE ESCRIBE 1 EN EL 5 DEL REGISTRO PARA PC1--EL VALOR 0X0020 REFIERE A HEX-- 10 PARA PC EN EXTI1

	EXTI->RTSR |= EXTI_RTSR_TR1;//CONFIGURACION DE FLANCO BAJADA--ESCRITURA DE 1


	__NVIC_EnableIRQ(EXTI1_IRQn);//REGISTRO LA INTERRPCION EN EL NVIC

	EXTI->PR |= EXTI_PR_PR1;//LIMPIEZA DE LA BANDERA RELACIONADA CON EL EXTI-SEGUN REFERENCE MANUAL SE LIMPIA CON 1

	EXTI->IMR |= EXTI_IMR_IM1;//ACTIVACION DE LA INTERRUPCION (IMR)- SE ESCRIBE 1 EN EL O-->PB0


	//BUSCAR LAS ISR --> STARTUP-->VECTORES COMPLETOS
	//

}
//ISR PARA EL EXTI0
// VERIFICAR QUE EL PR ESTA LEVATADO
//
void EXTI1_IRQHandler(void){		// SE INDICA QUE SE VA A SER Y EN EL MAIN SE HACE
	if(EXTI->PR && EXTI_PR_PR1){ 	//VERIFICACION
		EXTI->PR |= EXTI_PR_PR1;	//LIMPIEZA DE INTERRPCION RELACIONADA CON EL EXTI
		increment_counter=1;		//VA A SER EVALUADA EN EL MAIN

	}
}

void separar_digitos(void) {
    digitos[0] = counter_exti / 1000;          // Millares (D1)
    digitos[1] = (counter_exti / 100) % 10;    // Centenas (D2)
    digitos[2] = (counter_exti / 10) % 10;     // Decenas (D3)
    digitos[3] = counter_exti % 10;            // Unidades (D4)
}

void decodificar_7seg(uint8_t numero) {
    // 1. APAGAR TODOS LOS SEGMENTOS PRIMERO (Poner en 1)
    GPIOC->ODR |= (GPIO_ODR_OD9 | GPIO_ODR_OD11 | GPIO_ODR_OD12 | GPIO_ODR_OD10 | GPIO_ODR_OD8);
    GPIOB->ODR |= (GPIO_ODR_OD8);
    GPIOD->ODR |= (GPIO_ODR_OD2);

    // 2. ENCENDER LOS NECESARIOS (Poner en 0)
    switch(numero) {
        case 0: // A, B, C, D, E, F
            GPIOC->ODR &= ~(GPIO_ODR_OD9 | GPIO_ODR_OD11 | GPIO_ODR_OD12 | GPIO_ODR_OD10 | GPIO_ODR_OD8);
            GPIOB->ODR &= ~(GPIO_ODR_OD8);
            break;
        case 1: // B, C
            GPIOC->ODR &= ~(GPIO_ODR_OD11);
            GPIOB->ODR &= ~(GPIO_ODR_OD8);
            break;
        case 2: // A, B, G, E, D
            GPIOC->ODR &= ~(GPIO_ODR_OD9 | GPIO_ODR_OD12 | GPIO_ODR_OD10);
            GPIOB->ODR &= ~(GPIO_ODR_OD8);
            GPIOD->ODR &= ~(GPIO_ODR_OD2);
            break;
        case 3: // A, B, G, C, D
            GPIOC->ODR &= ~(GPIO_ODR_OD9 | GPIO_ODR_OD11 | GPIO_ODR_OD12);
            GPIOB->ODR &= ~(GPIO_ODR_OD8);
            GPIOD->ODR &= ~(GPIO_ODR_OD2);
            break;
        case 4: // F, B, G, C
            GPIOC->ODR &= ~(GPIO_ODR_OD8 | GPIO_ODR_OD11);
            GPIOB->ODR &= ~(GPIO_ODR_OD8);
            GPIOD->ODR &= ~(GPIO_ODR_OD2);
            break;
        case 5: // A, F, G, C, D
            GPIOC->ODR &= ~(GPIO_ODR_OD9 | GPIO_ODR_OD8 | GPIO_ODR_OD11 | GPIO_ODR_OD12);
            GPIOD->ODR &= ~(GPIO_ODR_OD2);
            break;
        case 6: // A, F, G, C, D, E
            GPIOC->ODR &= ~(GPIO_ODR_OD9 | GPIO_ODR_OD8 | GPIO_ODR_OD11 | GPIO_ODR_OD12 | GPIO_ODR_OD10);
            GPIOD->ODR &= ~(GPIO_ODR_OD2);
            break;
        case 7: // A, B, C
            GPIOC->ODR &= ~(GPIO_ODR_OD9 | GPIO_ODR_OD11);
            GPIOB->ODR &= ~(GPIO_ODR_OD8);
            break;
        case 8: // A, B, C, D, E, F, G (Todos)
            GPIOC->ODR &= ~(GPIO_ODR_OD9 | GPIO_ODR_OD11 | GPIO_ODR_OD12 | GPIO_ODR_OD10 | GPIO_ODR_OD8);
            GPIOB->ODR &= ~(GPIO_ODR_OD8);
            GPIOD->ODR &= ~(GPIO_ODR_OD2);
            break;
        case 9: // F, A, B, G, C
            GPIOC->ODR &= ~(GPIO_ODR_OD8 | GPIO_ODR_OD9 | GPIO_ODR_OD11);
            GPIOB->ODR &= ~(GPIO_ODR_OD8);
            GPIOD->ODR &= ~(GPIO_ODR_OD2);
            break;
    }
}

void TIM2_IRQHandler(void){
    if (TIM2->SR & TIM_SR_UIF){
        TIM2->SR &= ~TIM_SR_UIF; // Limpiar bandera

        // 1. APAGAR TODOS LOS DÍGITOS (Transistores PNP a 1) para evitar "efecto fantasma"
        GPIOC->ODR |= (GPIO_ODR_OD13 | GPIO_ODR_OD6);
        GPIOB->ODR |= (GPIO_ODR_OD9 | GPIO_ODR_OD7);

        // 2. CONFIGURAR LOS SEGMENTOS para el dígito actual
        decodificar_7seg(digitos[digito_actual]);

        // 3. ENCENDER SOLO EL DÍGITO ACTUAL (Transistor PNP a 0)
        if (digito_actual == 0) GPIOC->ODR &= ~GPIO_ODR_OD13; // D1
        else if (digito_actual == 1) GPIOC->ODR &= ~GPIO_ODR_OD6;  // D2
        else if (digito_actual == 2) GPIOB->ODR &= ~GPIO_ODR_OD9;  // D3
        else if (digito_actual == 3) GPIOB->ODR &= ~GPIO_ODR_OD7;  // D4

        // 4. PASAR AL SIGUIENTE DÍGITO
        digito_actual++;
        if (digito_actual > 3) {
            digito_actual = 0; // Reiniciar ciclo
        }
    }
}
void configurar_timer2_display(void){
	// Activar bus del TIM2
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	TIM2->PSC = 16000 - 1; // Tick de 1 ms
	TIM2->ARR = 7 - 1;     // Interrupción cada 7 ms (Para refresco rápido)

	TIM2->CNT = 0;

	TIM2->DIER |= TIM_DIER_UIE; // Interrupción de actualización

	__NVIC_EnableIRQ(TIM2_IRQn); // Matricular TIM2 en el NVIC

	TIM2->CR1 &= ~(TIM_CR1_DIR);
	TIM2->CR1 |= TIM_CR1_ARPE;
	TIM2->CR1 |= TIM_CR1_CEN; // Arrancar Timer 2
}


